### ISSUE TITLE
Bug: No crystal orientation output

### ISSUE THREAD

**Issue by fzw9381** [neperfepx/FEPX#22] opened 2021-06-22 14:50 UTC
In example 1, when the number of crystal grains is modified to 1, and the ori result is output in the post-processing. I found that the ori results are all 0, even if the initial grain orientation is not 0. This is a bug found in the latest version 1.2.0, but there is no such bug in the previous version.

**Comment by acmelab-ua** [comment] 2021-06-22 16:07
I am unable to reproduce locally - can you please provide a minimal working example?

**Comment by fzw9381** [comment] 2021-06-23 01:37
https://github.com/fzw9381/My-questions/raw/main/examples1_with_one_grain.zip

there is the example files. You can see the ori results are all zero.

**Comment by acmelab-ua** [comment] 2021-06-23 01:41
The link is broken (404 error), likely due to being private.

**Comment by fzw9381** [comment] 2021-06-23 01:45
https://github.com/fzw9381/My-questions/raw/main/examples1_with_one_grain.zip

Sorry, try this link

**Comment by acmelab-ua** [comment] 2021-06-23 01:53
OK, I can reproduce. Let me look into this.

**Comment by acmelab-ua** [comment] 2021-06-23 02:17
@fzw9381: I have found the issue, and will attempt to patch this tomorrow.

In the meantime, if you would like to fix it locally to continue your work, the issue lies on lines 168, 180, 191, 202, and 213 of `microstructure_mod.f90`. Each instance of `I+1` on these lines should be edited to be just `I`, e.g.: `WHERE (I .EQ. MY_UESUB)`.

**Comment by fzw9381** [comment] 2021-06-23 02:45
Thanks a lot. Let me try this. Looking forward to your patch.

**Comment by mkasemer** [comment] 2021-06-25 13:29
@fzw9381 This issue has been fixed in [v1.2.1](https://github.com/acmelab-ua/FEPX/releases/tag/v1.2.1).

**Closed as completed by mkasemer** 2021-06-25 13:29 UTC
